revert conditional

diff --git a/tools/rebuild-image b/tools/rebuild-image
--- a/tools/rebuild-image
+++ b/tools/rebuild-image
@@ -42,10 +42,10 @@ commit_timestamp() {
 
 # is the SHA1 actually present in the repo?
 # it could be it isn't, e.g. after a force push
-commit_invalid() {
+commit_valid() {
 	local rev=$1
 	git rev-parse --quiet --verify "$rev^{commit}"
-	[ $? -ne 0 ]
+	[ $? -eq 0 ]
 }
 
 cached_revision=$(cached_image_rev)
@@ -55,8 +55,8 @@ if [ -z "$cached_revision" ]; then
 	exit 0
 fi
 
-if commit_invalid "$cached_revision"; then
-  echo ">>> cached commit invalid, rebuilding"
+if ! commit_valid "$cached_revision"; then
+  echo ">>> cached SHA1 not found in repo, rebuilding"
   rebuild
   exit 0
 fi
