Check if SHA1 exists before calling `git diff`

diff --git a/tools/rebuild-image b/tools/rebuild-image
--- a/tools/rebuild-image
+++ b/tools/rebuild-image
@@ -40,11 +40,25 @@ commit_timestamp() {
 	git show -s --format=%ct "$rev"
 }
 
+# is the SHA1 actually present in the repo?
+# it could be it isn't, e.g. after a force push
+commit_invalid() {
+	local rev=$1
+	git rev-parse --quiet --verify "$rev^{commit}"
+	[ $? -ne 0 ]
+}
+
 cached_revision=$(cached_image_rev)
 if [ -z "$cached_revision" ]; then
 	echo ">>> No cached image found; rebuilding"
 	rebuild
 	exit 0
+fi
+
+if commit_invalid "$cached_revision"; then
+  echo ">>> cached commit invalid, rebuilding"
+  rebuild
+  exit 0
 fi
 
 echo ">>> Found cached image rev $cached_revision"
